"""adress

Revision ID: 421d8d3ccf07
Revises: 5ab7b67c6212
Create Date: 2021-12-29 17:15:13.260502

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '421d8d3ccf07'
down_revision = '5ab7b67c6212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###    
    op.create_table('adress',
    sa.Column('cep', sa.Integer(), nullable=False),
    sa.Column('street', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adress_cep'), 'adress', ['cep'], unique=False)
    op.create_index(op.f('ix_adress_id'), 'adress', ['id'], unique=False)
    op.create_index(op.f('ix_adress_street'), 'adress', ['street'], unique=False)
    op.create_index(op.f('ix_adress_number'), 'adress', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###    
    op.drop_index(op.f('ix_adress_cep'), table_name='adress')
    op.drop_index(op.f('ix_adress_id'), table_name='adress')
    op.drop_index(op.f('ix_adress_street'), table_name='adress')
    op.drop_index(op.f('ix_adress_number'), table_name='adress')
    op.drop_table('adress')
    # ### end Alembic commands ###
